# ==========================================
# UNIVERSAL FRAGMENTOMICS WORKFLOW CONFIG
# ==========================================

directories:
  input: "data/raw_bed"   # Name of the folder containing your input data
  output: "results"       # Output intermediate files (extracted features and alignments)
  ml_output: "ml_output"  # Directory for ML plots and reports

pipeline:
  # The starting format of your inputs. 
  # Supported values: "fastq" | "bam" | "bed"
  # - "fastq": Will trigger adapter trimming and multi-mapping
  # - "bam": Will trigger conversion to bed mapped coordinates
  # - "bed": Will directly extract fragmentomics metrics
  input_type: "bed"       

machine_learning:
  # The baseline/control class to evaluate experimental classes against.
  # Crucial for computing Binary ROC-AUC metrics and drivers.
  baseline_class: "Normal"
